---
version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: .Dockerfile-compose
#      args:
#        CI_REPOSITORY: ${CI_REPOSITORY}
#        CI_REGISTRY_USER: ${CI_REGISTRY_USER}
#        CI_REGISTRY_PASSWORD: ${CI_REGISTRY_PASSWORD}
    env_file: .env
    container_name: siged_web
    hostname: localhost
    ports:
      - "8080:8080"
#    volumes:
#      - "${APP_LOCAL_MATERIAL_PATH}:${VOL_MATERIAL_PATH}"
    networks:
      - bridge_mode
    shm_size: "256m"

networks:
  bridge_mode:
    driver: bridge
