#FROM eclipse-temurin:8-jdk-focal
#RUN mkdir app
#ADD . /app
#WORKDIR /app
#CMD ./mvnw clean package
#ENTRYPOINT java -jar target/siged-3.9.24-SNAPSHOT.jar

FROM maven:3.3-jdk-8 as builder
COPY . /usr/src/mymaven
WORKDIR /usr/src/mymaven
RUN mvn clean install -f /usr/src/mymaven && mkdir /usr/src/wars/
RUN find /usr/src/mymaven/ -iname '*.war' -exec cp {} /usr/src/wars/ \;
#
FROM tomcat:7.0.90-jre8
RUN rm -rf /usr/local/tomcat/webapps/*
COPY --from=builder /usr/src/wars/siged-3.9.24-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war